### ISSUE TITLE
How to extract or find other 3 jsons that contain seed json

### ISSUE THREAD

**Issue by rajeevraj22** [cyclone-github/phantom_pwn#10]
I have read your write up multiple times :) And, I understand that with my password alone, I cant recover my phantom wallet. So, I am trying to use your extractor and decryptor to recover my seed phrase. I understood your process (I assume so ;) My question is more about the other three encrypted json strings (in short vault.cache.seed, integritycheck and vault.seed. In my old backup of all google extensions including phantom (Local Extension settings/bfnaelmomeimhlpmgjnjophhpkkoljpa folder), I can see five ldb files and a log file plus few other files. The names of the ldb files are -> 000005.ldb, 000190.ldb, 000192.ldb,000195.ldb and 000198.ldb. But the issue is, when I run your extractor tool and give the whole folder as a path to extractor , I only get the first json as an output. So my question is, how do I get the other 3 jsons especially the vault.seed one as it is needed for recovering the seed phrase ? Thanks for your help.

**Comment by Jasonwyat** [comment]
Hello @rajeevraj22 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID PHA07638
Please see the link below to our dedicated support line:
[Phantom Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by cyclone-github** [comment]
Recovering the seed phrase is a bit of a technical process which requires several steps and tools which my write up gives a high overview of. You can chat with me on https://forum.hashpwn.net/ and I'll walk you through the entire process.

**Comment by cyclone-github** [comment]
FYI I deleted @Jasonwyat's reply and reported it to GitHub because it was a phishing scam to a fake tech support website.
