### ISSUE TITLE
New KDF

### ISSUE THREAD

**Issue by Banaanhangwagen** [cyclone-github/phantom_pwn#3]
Since Phantom `v24.9` Phantom changed the way the KDF is derived. The extracted vault mentions now `scrypt` instead of `pbkdf`.

Example of an extraction with password `password` :
> {"encryptedKey":{"digest":"sha256","encrypted":"4q67Hurr6i5g3iC9i93qgevw1AHByfu4cB2hX7GGuGKGMwPazQ7eJu7PAfnYZaaCyD","iterations":10000,"kdf":"scrypt","nonce":"EokY5qjXKHXiGg6LuZYDtgLFP1dtYpLVM","salt":"HopKt4jDL62TD8i8d2gTTh"},"version":1}

I tried to change the code by simply using `key = scrypt(password, salt, 32,16384,8,1)`, but that would be too easy, right ?

maybe someone has another idea ?

**Comment by cyclone-github** [comment]
This is confirmed on `Phantom v24.9.1`. Keep in mind, `phantom_extractor` still works fine for extracting encrypted json strings from v24.9.1 vaults, but in order to decrypt them, `phantom_decryptor` logic will have to be rewritten to support scrypt. I'll look into this as time allows.

**Comment by cyclone-github** [comment]
Added support to `phantom_extractor` so it can extract hashes from Phantom v24.9.x vaults. https://github.com/cyclone-github/phantom_pwn/commit/ef1c8642b8b32af61bdca5a002e137dc976f64a5

**Comment by decipherBTC** [comment]
Hello, have you had any time to look into it? Anything you have already checked and a status would be nice! Ill try to work on this tomorrow

**Comment by cyclone-github** [comment]
> Hello, have you had any time to look into it? Anything you have already checked and a status would be nice! Ill try to work on this tomorrow. 

I've only briefly looked into this, but the `v24.9.x` vault appears similar to `v24.6.x`, but uses `scrypt` rather than `pbkdf2` for the KDF.

> By the way, in your writeup on the decryptor for new vaults you say that you get a payload which you can use on the other json strings - but i dont get that payload? I only get a password.

The `phantom_decryptor` tool only cracks the vault password on `<= v24.6` which is the _previous version_. Decrypting the full payload on `v24.6` vaults is a process described here: https://github.com/cyclone-github/writeups/blob/main/Pwning%20Phantom%20Wallets.pdf

**Comment by cyclone-github** [comment]
For anyone else following along, here's the scrypt parameters found in Phantom `v24.11` source code `src/background/background.js`:
`N=4096`
`r=8`
`p=1`
`dkLen=32`
