### ISSUE TITLE
how to get base64 string

### ISSUE THREAD

**Issue by juietafayeihsus** [cyclone-github/phantom_pwn#7]
![Screenshot-2024-12-01-at-22 28 05](https://github.com/user-attachments/assets/fc8a2fe4-5a7f-482d-9223-e358e547211c)

I looked at your writeup but when I use decrypt it doesn't output the base64 code like yours : fp+UEdf3RUtAqxtxEMjWQJKStHO9HnaoOoN7Robaj3k=

**Comment by cyclone-github** [comment]
The `phantom_pwn` toolset can extract and crack a Phantom vault hash, enabling users to retrieve or verify their password. However, it does not output the decrypted payload or recover the seed phrase as that process is complex and involves multiple steps to complete as mentioned in the writeup.

The writeup provides a high-level summary of the steps used to decrypt newer Phantom wallets and extract the seed phrase. It does not include all of the necessary code or detailed instructions as this process is complex, varies on the version of the Phantom wallet being recovered, and requires multiple stages to complete.
[writeup link](https://github.com/cyclone-github/writeups/blob/main/Pwning%20Phantom%20Wallets.pdf)
