### ISSUE TITLE
file not found 

### ISSUE THREAD

**Issue by Red-Devils-Workshop** [cyclone-github/phantom_pwn#8]
Im having trouble getting it to fun. new at all this but lost my password to my account and need this to help get it back. are you able to send a video to me on how you set it up and got it to fun?

**Comment by Red-Devils-Workshop** [comment]
same with the Decryptor plz would be much help! you can send it to me if you dont want to post it.

**Comment by cyclone-github** [comment]
All of the compile and run info is in the README.
You can contact me on https://forum.hashpwn.net and I'll walk you through setting up and running the toolset.
